# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 21:56
from __future__ import unicode_literals

from django.db import migrations
import djangocms_attributes_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_filer_file', '0002_auto_20160112_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='filerfile',
            name='link_attributes',
            field=djangocms_attributes_field.fields.AttributesField(default=dict, help_text='Optional. Adds HTML attributes to the rendered link.'),
        ),
    ]
